CREATE TABLE BIBLIOTECA.AUTORES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    NACIONALIDADE VARCHAR(50)
);

CREATE TABLE BIBLIOTECA.LIVROS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(150) NOT NULL,
    ID_AUTOR INT NOT NULL,
    GENERO VARCHAR(50),
    FOREIGN KEY (ID_AUTOR) REFERENCES AUTORES(ID) ON DELETE CASCADE
);